version: "2"
run:
  go: "1.23"
linters:
  default: none
  enable:
    - err113
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unparam
    - unused
  settings:
    gocritic:
      disabled-checks:
        - ifElseChain
      enabled-tags:
        - diagnostic
        - style
        - performance
    revive:
      rules:
        - name: exported
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - err113
          - errcheck
          - gocritic
          - unparam
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
