import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {fileURLToPath} from 'node:url';import {spawnSync} from 'node:child_process';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'archify-sequence-er-test-'));
const example=JSON.parse(fs.readFileSync(path.join(root,'examples/join-update-delete.sequence-er.json')));
function run(command,input,out){return spawnSync(process.execPath,[path.join(root,'bin/archify.mjs'),command,'sequence-er',input,...(out?[out]:[]),'--repo-root',root,'--quality','showcase','--json'],{encoding:'utf8'})}
function input(d,name){const p=path.join(tmp,name+'.json');fs.writeFileSync(p,JSON.stringify(d));return p}
test('SELECT JOIN, UPDATE and DELETE input delivers a standalone artifact',()=>{const out=path.join(tmp,'valid.html'),r=run('deliver',input(example,'valid'),out);assert.equal(r.status,0,r.stdout+r.stderr);const h=fs.readFileSync(out,'utf8');assert.equal((h.match(/<svg\b/g)||[]).length,1);assert(h.includes('data-role-toggle="delete"'));assert(h.includes('data-section="er"'));assert(h.includes('data-node-id="seq-core"')||h.includes('data-node-id="seq-app"'));assert(h.includes('data-node-id="er-tasks"'))});
for(const [name,mutate] of [
 ['unknown column',d=>d.accesses[0].read.push('tasks.missing')],['unknown message',d=>d.accesses[0].message='missing'],['duplicate message binding',d=>d.accesses[1].message=d.accesses[0].message],['unknown relation',d=>d.accesses[0].relations[0].id='missing'],['source mismatch',d=>d.accesses[0].source.quote='not the SQL'],['path traversal',d=>d.accesses[0].source.path='../secret'],['DELETE cannot be column update',d=>d.accesses[2].write=['tasks.state']],['SELECT cannot delete rows',d=>d.accesses[0].delete=['tasks']],['missing DDL',d=>d.evidence=[]],['default must exist',d=>d.default='missing'],['ER needed for accesses',d=>delete d.er],['unsupported property',d=>d.typo=true]])test(name+' fails and retains an existing artifact',()=>{const d=structuredClone(example);mutate(d);const out=path.join(tmp,name.replaceAll(' ','-')+'.html');fs.writeFileSync(out,'last good artifact');const r=run('deliver',input(d,name.replaceAll(' ','-')),out);assert.notEqual(r.status,0);assert.equal(fs.readFileSync(out,'utf8'),'last good artifact')});
test('sequence-only produces no ER panel or role switches',()=>{const d=JSON.parse(fs.readFileSync(path.join(root,'examples/sequence-only.sequence-er.json'))),out=path.join(tmp,'sequence-only.html');const r=run('deliver',input(d,'sequence-only'),out);assert.equal(r.status,0,r.stdout+r.stderr);const svg=fs.readFileSync(out,'utf8').match(/<svg\b[\s\S]*?<\/svg>/)[0];assert(!/data-section="er"|data-role-toggle|data-entity-id/.test(svg));assert(svg.includes('GET /health'))});
test.after(()=>fs.rmSync(tmp,{recursive:true,force:true}));
test('sequence and ER may share source IDs without sharing viewer IDs',()=>{const d=structuredClone(example),id=d.sequence.messages[0].id;d.er.relationships[0].id=id;d.accesses[0].relations[0].id=id;const out=path.join(tmp,'collision.html'),r=run('deliver',input(d,'collision'),out);assert.equal(r.status,0,r.stdout+r.stderr);const h=fs.readFileSync(out,'utf8');assert(h.includes(`data-edge-id="seq-${id}"`));assert(h.includes(`data-edge-id="er-${id}"`));assert(!h.includes(`data-edge-id="${id}"`))});
test('sequence-only guided focus uses original participant ID',()=>{const d=JSON.parse(fs.readFileSync(path.join(root,'examples/sequence-only.sequence-er.json'))),id=d.sequence.participants[0].id;d.meta.views=[{id:'api',label:'API',focus:[id]}];const out=path.join(tmp,'guided.html'),r=run('deliver',input(d,'guided'),out);assert.equal(r.status,0,r.stdout+r.stderr);const h=fs.readFileSync(out,'utf8');assert(h.includes(`data-node-id="${id}"`));d.meta.views[0].focus=['seq-'+id];assert.notEqual(run('validate',input(d,'bad-guided')).status,0)});
