export const css = `
.phase-nav{display:flex;gap:10px;flex-wrap:wrap;margin:10px -29.5rem 0 0;font-size:12px}.phase-nav a{color:var(--text-muted);text-decoration:none;padding:4px 2px;border-bottom:2px solid transparent}.phase-nav a[aria-current]{color:var(--text);border-color:var(--frontend-stroke)}@media(max-width:720px){.phase-nav{margin-right:0}}
.access-hit{fill:transparent;stroke:transparent;cursor:pointer}[data-access-active]>.access-hit{fill:var(--backend-fill);stroke:var(--backend-stroke)}[data-access-id]:focus-visible>.access-hit{stroke:var(--frontend-stroke);stroke-width:3}
.access-column{fill:transparent;pointer-events:none}.access-column[data-access-role=read]{fill:var(--backend-fill);stroke:var(--backend-stroke)}.access-column[data-access-role=filter]{fill:var(--cloud-fill);stroke:var(--cloud-stroke)}.access-column[data-access-role=join]{fill:var(--frontend-fill);stroke:var(--frontend-stroke)}.access-column[data-access-role=write]{fill:var(--security-fill);stroke:var(--security-stroke)}
.access-role-strip{display:none;pointer-events:none}.access-role-strip[data-visible]{display:inline}.access-role-strip[data-role=read]{fill:var(--backend-stroke)}.access-role-strip[data-role=filter]{fill:var(--cloud-stroke)}.access-role-strip[data-role=join]{fill:var(--frontend-stroke)}.access-role-strip[data-role=write]{fill:var(--security-stroke)}
[data-delete-target] .body{stroke:var(--security-stroke);stroke-width:4}.delete-label{display:none;fill:var(--security-stroke);font-size:9px;font-weight:700;text-anchor:end}[data-delete-target] .delete-label{display:inline}
.er-edge[data-access-relation=inner],.er-edge[data-access-relation=left]{stroke:var(--frontend-stroke);stroke-width:3;stroke-dasharray:none}.er-edge[data-access-relation=subquery]{stroke:var(--frontend-stroke);stroke-width:3;stroke-dasharray:3 5}
.access-panel-title{fill:var(--text);font-size:18px;font-weight:700}.access-caption{fill:var(--text-muted);font-size:11px}.access-key{fill:var(--text);font-size:12px}.role-toggle-hit{fill:var(--panel);stroke:var(--panel-border);cursor:pointer}[data-role-toggle]{cursor:pointer}[data-role-toggle][aria-pressed=true] .role-toggle-hit{fill:var(--frontend-fill);stroke:var(--frontend-stroke)}[data-role-toggle][aria-pressed=false]{opacity:.55}[data-role-toggle]:focus-visible .role-toggle-hit{stroke-width:3}
`;
export const runtime = `(()=>{
'use strict';const page=JSON.parse(document.getElementById('sequence-er-data').textContent),svg=document.querySelector('.diagram-container svg'),all=['read','filter','join','write','delete'];let enabled=all.slice(),current;
const byId=id=>document.getElementById(id),edge=id=>Array.from(svg.querySelectorAll('[data-section=er] [data-edge-id]')).find(e=>e.getAttribute('data-edge-id')==='er-'+id);
function animate(){svg.querySelectorAll('[data-cleanup-flow]').forEach(e=>e.remove());if(!enabled.includes('join')||matchMedia('(prefers-reduced-motion:reduce)').matches||document.documentElement.getAttribute('data-motion')==='still')return;
current.relations.forEach(r=>{const e=edge(r.id),g=document.createElementNS(svg.namespaceURI,'g'),p=e.cloneNode(false);g.setAttribute('data-cleanup-flow','');g.setAttribute('data-relationship-pulse-overlay','');g.setAttribute('class','relationship-pulse-overlay');Array.from(p.attributes).forEach(a=>{if(a.name!=='d')p.removeAttribute(a.name)});p.setAttribute('class','intent-trace-flow');p.setAttribute('data-direction','out');p.setAttribute('pathLength','1');g.appendChild(p);e.parentNode.appendChild(g);g.addEventListener('animationend',()=>g.remove(),{once:true});setTimeout(()=>g.remove(),1500)})}
function select(a){current=a;svg.setAttribute('data-selected-access',a.id);svg.querySelectorAll('[data-access-id]').forEach(e=>{const active=e.getAttribute('data-access-id')===a.id;e.toggleAttribute('data-access-active',active);e.setAttribute('aria-pressed',String(active))});
svg.querySelectorAll('[data-column-ref]').forEach(e=>{const key=e.getAttribute('data-column-ref'),roles=all.slice(0,4).filter(r=>enabled.includes(r)&&a[r].includes(key)),primary=['write','filter','join','read'].find(r=>roles.includes(r));if(primary){e.setAttribute('data-access-role',primary);e.setAttribute('data-access-roles',roles.join(' '))}else{e.removeAttribute('data-access-role');e.removeAttribute('data-access-roles')}});
svg.querySelectorAll('[data-column-strip]').forEach(e=>e.toggleAttribute('data-visible',enabled.includes(e.getAttribute('data-role'))&&a[e.getAttribute('data-role')].includes(e.getAttribute('data-column-strip'))));svg.querySelectorAll('[data-entity-id]').forEach(e=>e.toggleAttribute('data-delete-target',enabled.includes('delete')&&a.delete.includes(e.getAttribute('data-entity-id'))));svg.querySelectorAll('[data-access-relation]').forEach(e=>e.removeAttribute('data-access-relation'));if(enabled.includes('join'))a.relations.forEach(r=>edge(r.id).setAttribute('data-access-relation',r.kind));
byId('access-title').textContent=a.id+' · '+a.title;byId('access-operation').textContent=a.operation+' · '+({SELECT:'読み取り',UPDATE:'列の更新',DELETE:'行の削除'}[a.operation]);byId('access-values').textContent=a.operation==='DELETE'?'削除対象：'+a.delete.join(', '):(a.operation==='SELECT'?'取得：':'更新：')+a[a.operation==='SELECT'?'read':'write'].length+'列（右図を参照）';byId('access-filter').textContent=a.filterText||'';byId('access-help').textContent=a.help||'';byId('access-relation').textContent=a.relationText||'';byId('access-source').textContent=a.source.path.split('/').pop()+':'+a.source.line;if(window.Archify?.focus)Archify.focus.clear()}
function handle(e){if(e.type==='keydown'&&!['Enter',' '].includes(e.key))return;const t=e.target.closest('[data-role-toggle]'),a=e.target.closest('[data-access-id]');if(!t&&!a)return;e.preventDefault();e.stopImmediatePropagation();if(t){const r=t.getAttribute('data-role-toggle');enabled=r==='all'?all.slice():enabled.length===1&&enabled[0]===r?[]:[r];svg.querySelectorAll('[data-role-toggle]').forEach(b=>b.setAttribute('aria-pressed',String(b.getAttribute('data-role-toggle')==='all'?enabled.length===5:enabled.includes(b.getAttribute('data-role-toggle')))));select(current)}else select(page.accesses.find(x=>x.id===a.getAttribute('data-access-id')));animate()}
svg.addEventListener('click',handle,true);svg.addEventListener('keydown',handle,true);select(page.accesses.find(a=>a.id===page.default)||page.accesses[0]);
})();`;
// Template clones geometry into the root SVG; include every enclosing panel transform.
export function patchGeometry(template){
 const matrix=owner=>`(function(m){return 'matrix('+[m.a,m.b,m.c,m.d,m.e,m.f].join(' ')+')';})(svg.getCTM().inverse().multiply(${owner}.getCTM()))`;
 return template.replace("clone.setAttribute('class', className || 'relationship-hit-rail');",`clone.setAttribute('transform',${matrix('shape')});clone.setAttribute('class', className || 'relationship-hit-rail');`)
 .replaceAll("if (edge.hasAttribute('transform')) wrapper.setAttribute('transform', edge.getAttribute('transform'));",`wrapper.setAttribute('transform',${matrix('edge')});`)
 .replace("clone.setAttribute('class', 'intent-trace-flow');","clone.removeAttribute('transform');clone.setAttribute('class', 'intent-trace-flow');")
 .replaceAll("if (firstNode) svg.insertBefore(overlay, firstNode);","if(firstNode){var layer=firstNode;while(layer.parentNode!==svg)layer=layer.parentNode;svg.insertBefore(overlay,layer);}")
 .replace("if (firstEdge && firstEdge.parentNode) firstEdge.parentNode.insertBefore(overlay, firstEdge);","if(firstEdge&&firstEdge.parentNode){var layer=firstEdge;while(layer.parentNode!==svg)layer=layer.parentNode;svg.insertBefore(overlay,layer);}");
}
